employee:
 build: Employee
 ports:
  - "8081"
 links:
  - mongodb
reward:
 build: Reward
 ports:
  - "8082"
 links:
  - mongodb
mission:
 build: Mission
 ports:
  - "8083"
 links:
  - mongodb
mongodb:
 image: mongo
ha_employee:
 image: tutum/haproxy
 links:
   - employee
 ports:
   - "8081:80"
ha_reward:
 image: tutum/haproxy
 links:
   - reward
 ports:
   - "8082:80"
ha_mission:
 image: tutum/haproxy
 links:
   - mission
 ports:
   - "8083:80"
