employee:
 build: Employee
 ports:
  - "8080"
 links:
  - mongodb
reward:
 build: Reward
 ports:
  - "8080"
 links:
  - mongodb
mission:
 build: Mission
 ports:
  - "8080"
 links:
  - mongodb
mongodb:
 image: mongo
ha_employee:
 image: tutum/haproxy
 links:
   - employee
 ports:
   - "8081:80"
